# Generated by Django 5.2.1 on 2025-07-26 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_add_coupon_fields'),
        ('orders', '0002_coupon_alter_order_payment_status_and_more'),
    ]

    operations = [
    ]
