# Generated by Django 5.2.1 on 2025-07-26 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_merge_20250726_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='min_order_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='最低消費金額才能使用此優惠碼', max_digits=10),
        ),
    ]
