# Generated by Django 5.2.1 on 2025-07-26 09:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_coupon_per_user_limit_alter_coupon_usage_limit_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CouponUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used_count', models.PositiveIntegerField(default=0, help_text='該用戶使用此優惠碼的次數')),
                ('first_used', models.DateTimeField(auto_now_add=True, help_text='首次使用時間')),
                ('last_used', models.DateTimeField(auto_now=True, help_text='最近使用時間')),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.coupon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '優惠碼使用記錄',
                'verbose_name_plural': '優惠碼使用記錄',
            },
        ),
        migrations.AlterUniqueTogether(
            name='couponusage',
            unique_together={('user', 'coupon')},
        ),
    ]
