# Generated by Django 5.2.1 on 2025-07-26 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20250726_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='usage_limit',
            field=models.PositiveIntegerField(blank=True, help_text='全站總使用次數限制，留空表示無限制', null=True),
        ),
    ]
